INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES (1001, 'USD', 'INR', 65, 0);
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES (1002, 'EUR', 'INR', 75, 0);
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES (1003, 'USD', 'BRL', 5, 0);